# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edge_report.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65\x64ge_report.proto\x12\x11smart_class.cloud\"\xa4\x01\n\x0cStatusReport\x12\x0f\n\x07\x65\x64ge_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63pu_percent\x18\x02 \x01(\x01\x12\x13\n\x0bnpu_percent\x18\x03 \x01(\x01\x12\x11\n\tmemory_mb\x18\x04 \x01(\x01\x12\x18\n\x10task_queue_depth\x18\x05 \x01(\x05\x12\x19\n\x11\x63onnected_devices\x18\x06 \x01(\x05\x12\x11\n\ttimestamp\x18\x07 \x01(\t\"6\n\x10HeartbeatRequest\x12\x0f\n\x07\x65\x64ge_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x9f\x01\n\nEdgeReport\x12G\n\x0cReportStatus\x12\x1f.smart_class.cloud.StatusReport\x1a\x16.smart_class.cloud.Ack\x12H\n\tHeartbeat\x12#.smart_class.cloud.HeartbeatRequest\x1a\x16.smart_class.cloud.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edge_report_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSREPORT']._serialized_start=41
  _globals['_STATUSREPORT']._serialized_end=205
  _globals['_HEARTBEATREQUEST']._serialized_start=207
  _globals['_HEARTBEATREQUEST']._serialized_end=261
  _globals['_ACK']._serialized_start=263
  _globals['_ACK']._serialized_end=280
  _globals['_EDGEREPORT']._serialized_start=283
  _globals['_EDGEREPORT']._serialized_end=442
# @@protoc_insertion_point(module_scope)
