# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import edge_report_pb2 as edge__report__pb2


class EdgeReportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportStatus = channel.unary_unary(
                '/smart_class.cloud.EdgeReport/ReportStatus',
                request_serializer=edge__report__pb2.StatusReport.SerializeToString,
                response_deserializer=edge__report__pb2.Ack.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/smart_class.cloud.EdgeReport/Heartbeat',
                request_serializer=edge__report__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=edge__report__pb2.Ack.FromString,
                )


class EdgeReportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReportStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeReportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStatus,
                    request_deserializer=edge__report__pb2.StatusReport.FromString,
                    response_serializer=edge__report__pb2.Ack.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=edge__report__pb2.HeartbeatRequest.FromString,
                    response_serializer=edge__report__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smart_class.cloud.EdgeReport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EdgeReport(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_class.cloud.EdgeReport/ReportStatus',
            edge__report__pb2.StatusReport.SerializeToString,
            edge__report__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_class.cloud.EdgeReport/Heartbeat',
            edge__report__pb2.HeartbeatRequest.SerializeToString,
            edge__report__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
